export default [
  { path: '/welcome', icon: 'home', component: './Welcome', name: 'AMSNet' },
  {
    path: '/user',
    layout: false,
    routes: [
      { path: '/user/login', component: './User/Login' },
      { path: '/user/register', component: './User/Register' },
    ],
  },
  {
    path: '/fileoperate',
    icon: 'edit',
    component: './FileOperate',
    name: 'Device Labeling',
    access: 'canUser',
  },
  {
    path: '/maskoperate',
    icon: 'edit',
    component: './MaskOperate',
    name: 'Net Labeling',
    access: 'canUser',
  },
  // {
  //   path: '/graphoperate',
  //   icon: 'edit',
  //   component: './GraphOperate',
  //   name: 'Knowledge Graph',
  //   access: 'canUser',
  // },
  // {
  //   path: '/floatwindow',
  //   icon: 'edit',
  //   component: './FloatWindow',
  //   name: 'floatwindow',
  //   access: 'canUser',
  // },
  {
    path: '/fileoperate-test',
    icon: 'edit',
    component: './FileOperate-Test',
    name: 'Device Labeling Test',
    access: 'canAdmin',
  },
  {
    path: '/maskoperate-test',
    icon: 'edit',
    component: './MaskOperate-Test',
    name: 'Net Labeling Test',
    access: 'canAdmin',
  },
  {
    path: '/graphoperate-test',
    icon: 'edit',
    component: './GraphOperate-Test',
    name: 'Knowledge Graph Test',
    access: 'canAdmin',
  },
  // {
  //   path: '/floatwindow-test',
  //   icon: 'edit',
  //   component: './FloatWindowTest',
  //   name: 'floatwindow Test',
  //   access: 'canAdmin',
  // },
  // {
  //   path: '/admin',
  //   icon: 'crown',
  //   name: '管理页',
  //   access: 'canAdmin',
  //   routes: [
  //     { path: '/admin', redirect: '/admin/user' },
  //     { icon: 'table', path: '/admin/user', component: './Admin/User', name: '用户管理' },
  //   ],
  // },
  { path: '/', redirect: '/welcome' },
  { path: '*', layout: false, component: './404' },
];
